# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
# https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts
# https://docs.github.com/en/actions/publishing-packages/publishing-docker-images
# https://github.com/marketplace/actions/pypi-publish

name: Tag Release Workflow

on:
  push:
    tags:
      - 'v*'


jobs:
  tests:
    uses: ./.github/workflows/test.yaml  # use the callable tests job to run tests
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: tests
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.8"
    - name: Build Package
      run: |
        echo python version: $(python --version)
        echo tag version ${GITHUB_REF##*/v}
        ./scripts/build ${GITHUB_REF##*/v}
    - uses: actions/upload-artifact@v4
      with:
        name: dist
        path: |
          dist/

  test-build:
    name: Test Build
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: "3.8"
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - name: Build and run tests
        run: |
          version=${GITHUB_REF##*/v}
          echo version ${version}
          pip install dist/*.whl
          pip install generify[test]
          python -c "import generify; assert generify.__version__ == '${version}', f'{generify.__version__} != ${version}'"
          pytest --pyargs generify

  pypi-publish:
    name: Publish package to PyPI
    runs-on: ubuntu-22.04
    needs: test-build
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: dist
        path: dist
    - name: Publish
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        packages-dir: dist
        user: __token__
        password: ${{ secrets.PYPITOKEN }}
        verbose: true
