# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategymatrix
# todo share py-version between tests as a matrix https://github.com/orgs/community/discussions/26284

name: Test Workflow

on:
  workflow_call:
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        py-version: [3.8, 3.12]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.py-version }}
      - name: Build and run tests
        run: |
          python --version
          python -m pip install .[test]
          python -m pytest . -v --junitxml=tmp/report-${{ matrix.py-version }}.xml
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: tmp/report-${{ matrix.py-version }}.xml
          check_name: report ${{ matrix.py-version }}
